sql:
  host: localhost
  port: 3306
  database: reportsystem
  username: root
  password:

messages:
  ban-command: /ipban %player% %reason%
  date-format: dd/MM/yyyy HH:mm:ss

# These are toggleable options you can enable/disable by settings the values to true/false.
toggleable:
  sounds: true # Enables a sound being sent to the player when they successfully report a user. A sound is also sent to the staff member when a report is made.
  alert: true # A message is also sent to the staff member when a report is made.
  use-ban-command: true # If enabled, the ban command will be executed when a report is accepted. The ban command is defined in the messages section above.
  show-date: true # If enabled, the date will be shown in the report list. The date format is defined in the messages section above.
