sql:
  host: localhost
  port: 3306
  database: reportsystem
  username: root
  password:

messages:
  ban-command: /ipban %player% [REPORT] %reason%
  date-format: dd/MM/yyyy HH:mm:ss
  prefix: 'XlX5»Xr'
  default-reason: '[REPORT] %player% - %reason%'

# These are toggleable options you can enable/disable by settings the values to true/false.
toggleable:
  sounds: true # Enables a sound being sent to the player when they successfully report a user. A sound is also sent to the staff member when a report is made.
  alert: true # A message is also sent to the staff member when a report is made.
  use-ban-command: true # If enabled, the ban command will be executed when a report is accepted. The ban command is defined in the messages section above.
  show-date: true # If enabled, the date will be shown in the report list. The date format is defined in the messages section above.

# Values regarding the discord bot. Some features won't work if these are left blank.
discord-bot:
  # The token of the discord bot. This is the most important part of the discord bot. If this is left blank, the bot won't work.
  token:

  # The ID of your server.
  guild-id:


  # The color of the embeds. This does not apply to the alert system embeds. Default is blue.
  embed-color: blue


  # The activity type of the discord bot. This can be PLAYING, WATCHING, LISTENING, STREAMING, COMPETING. Example: "Playing Minecraft"
  # PLAYING, WATCHING, LISTENING, STREAMING, COMPETING
  activity-type: PLAYING

  # If the activity type is set to STREAMING, you must also set the following. Make sure to uncomment the line below
  # streaming-link: https://twitch.tv/discord


  # The message that will be displayed in the activity.
  activity-message: Minecraft

  # The Status of the discord bot. This can be ONLINE, IDLE, DND, INVISIBLE. Example: "Online" will show a green circle.
  # ONLINE, IDLE, DND, INVISIBLE
  status-type: ONLINE

  # the id of the channel where alerts will be sent. If left blank, alerts will not be sent.
  alerts-channel-id:

  # the id of the role which allows users to use moderator commands. If left blank, these commands won't work.
  staff-role-id:
